### PR TITLE
Allow additional options for request-promise.

### PR DESCRIPTION
**Pull request by Andrey-Kovinjonok**

### CODE REVIEW

**Comment by 0xR** [comment]
What is the usecase of this?

Tbh I think we should make the whole data fetching pluggable which would allow you to pass in your own options and even chose whether you're going to use request-promise, node-fetch or something else.

**Comment by Andrey-Kovinjonok** [comment]
As you can see bellow by link the request has set of options. 
https://github.com/request/request#requestoptions-callback

And as example I have tried to decode gzip'ed traffic by `const requestOptions = { gzip: true };`

**Comment by Andrey-Kovinjonok** [comment]
But may be the best way to pass initial graphQL schema options like object
`graphQLSchema({
  pathToSwaggerSchema,
  proxyUrl,
  customHeaders,
  requestOptions,
})`

**Comment by yarax** [comment]
@0xR that would be quit painful to write converters from swagger to all possible http libs options

**Comment by TimSusa** [comment]
For me this pull request sounds quite useful. I miss possibilities to set stuff like in https://github.com/swagger-api/swagger-js. At the moment we use this in our hand crafted GraphQL API´s to make calls in the resolvers. A lot of stuff has to be reconfigured. It would be fantastic to have those possibilites with swagger-to-graphql. I think a fetch like interface is very popular to most developers.

**Comment by 0xR** [comment]
We don't have to support all http libs. We can provide a URL, headers and a
request body and users can patch this in their own library however they
want. We can still default on request-promise but allow any override, like
node-fetch, as well.

Op vr 15 jun. 2018 15:28 schreef Roman Krivtsov <notifications@github.com>:

**Comment by 4F2E4A2E** [comment]
@0xR please provide a example, that would be helpful

**Comment by 0xR** [comment]
Something like this:

```
  const myFetcher = (url, fetchOptions) => {
    fetch(url, { ...fetchOptions, otherOption: 'new value' });
  }
  app.use('/graphql', graphqlHTTP(() => {
    return {
      schema,
      graphiql: true,
      fetch: myFetcher
    };
  }));
```

**Comment by yarax** [comment]
True, also it makes possible to use unit tests with DI for us. But in most cases users just need to pass additional headers and writing the request function would be overkill for them. so probably it would make sense to have transformed function for those arguments and the request function to pass through, and all of them are optional

**Comment by 0xR** [comment]
I'm sure we can think of something userfriendly. If we have the callback we can implement any userfriendlyness by just providing our own callbacks.

If only I had time to implement all this...

**Comment by yarax** [comment]
But in any case user will have to map path, query string, headers and body manually to its own HTTP function. So it's still fine for people who really want a deep customization and we can do it, but if you want to add just an editional header and don't care about HTTP implementation, then probably transform function like
```
({path, headers, qs, body}) => {path, headers, qs, body}
```
would be more useful. So we give give both possibilities

**Comment by ateamlunchbox** [comment]
+1 on this (and BTW: thanks for the great library).

I want to be able to modify the request options at the time the request-promise object is created.  I was thinking a callback function would be ideal: it would get passed the 'req' object before it is used to create the request-promise.

Something like this (adapted from index.js):

```javascript
// ADDITIONAL ARGUMENT 'reqFunc'
const resolver = (endpoint: Endpoint, proxyUrl: ?(Function | string), customHeaders = {}, reqFunc = null) =>
  async (_, args: GraphQLParameters, opts: SwaggerToGraphQLOptions) => {
    const proxy = !proxyUrl ? opts.GQLProxyBaseUrl : (typeof proxyUrl === 'function' ? proxyUrl(opts) : proxyUrl);
    const req = endpoint.request(args, proxy);
    if (opts.headers) {
      const { host, ...otherHeaders } = opts.headers;
      req.headers = Object.assign(customHeaders, req.headers, otherHeaders);
    }
    // UPDATED LINE HERE
    const res = await rp(reqFunc == null ? req : reqFunc(req));
    return JSON.parse(res);
  };
```

My intention is to be able to have an opportunity to modify the 'req' object before it is actually used to create the request-promise.

**Comment by ZiggyQubert** [comment]
I agree with @ateamlunchbox having a callback to give access view and modify the full request object before sending is a way better way to go.

As an example, a project I'm working on needs to sign the service calls before sending them incorporating the full path + query parameters and a hashed version of the body which currently there is no way to do, in addition I also have to implement the gzip: true flag for the request.

Simply allowing for additional parameters to be added to the request creation as @Andrey-Kovinjonok has done doesn't cover enough use cases.

**Comment by bwalsh** [comment]
Tanks for a great library.   I'd like to be able to compose a new schema and call resolvers exposed here by the remote REST endpoint.  Is that possible ?

**Pull request closed without merging**
