### PR TITLE
Improve support es6 features for node v4

### PR DESCRIPTION
**Pull request by marla-singer**
### Background

I've used MeteorJS framework where the version of node is 4 and it can be upgraded only by framework's developers. And I found your files don't work properly with node v4. 

It throws error `"regeneratorRuntime is not defined"`

I prepared changes to supporting node v4.

### Changes
- Removed old package `babel-polyfill`and install new plugin that works properly with async\await
- Recompile files

### CODE REVIEW

**Comment by yarax** [comment]
Hi! Thanks for the great PR! Unfortunately didn't see the notification about it, so didn't respond earlier.

**Comment by yarax** [comment]
Published as v1.1.5

**Comment by marla-singer** [comment]
@yarax Cool :+1: Attention please on another your library -- https://github.com/yarax/node-request-by-swagger/pull/1

**Comment by yarax** [comment]
Yep, merged. The new dependency is included to v1.1.6

**Pull request merged**
