### PR TITLE
A fix and a couple of new features

### PR DESCRIPTION
**Pull request by mihaislobozeanu**
1. fix for references. json-schema-ref-parser doesn't use $ref field for references.
2. path can be an url and the swagger schema will be fetched
3. if GQLProxyBaseUrl is not provided, take the baseUrl from swagger schema
4. allow multiple swagger schema and join them using namespaces

### CODE REVIEW

**Comment by mihaislobozeanu** [comment]
I hope this time we don't have the indent issue.

Thanks,
Mihai

**Comment by yarax** [comment]
Seems like they are still there. Just check `Files changes` tab

**Comment by mihaislobozeanu** [comment]
Please check only the files from src and not from lib. I've recheck those files and there is no problem with indentation.

**Comment by mihaislobozeanu** [comment]
Any news?

**Comment by yarax** [comment]
now there are tabs instead of spaces and please don't build and commit lib files, the project is built before publishing

**Comment by mihaislobozeanu** [comment]
If it is so, why don't you remove the lib files from git?

**Comment by kavink** [comment]
ping...

**Comment by kavink** [comment]
@mihaislobozeanu possible to resolve merge conflict ?

**Comment by abhishekghosh1** [comment]
@mihaislobozeanu do you have any plan to merge it soon? Also it would be helpful if you update the docs or write tests about multiple swagger schema.

**Comment by yarax** [comment]
I'm closing it, because it still contains conflicts and some of the features already done by other PRs. Also please, suggest small changes except of big ones, it's much easy to manage and accord to issues. Thanks!

**Pull request closed without merging**
