### PR TITLE
allow circular references, use definition types, update test framework

### PR DESCRIPTION
**Pull request by ofersadgat**
This fixes https://github.com/yarax/swagger-to-graphql/issues/33 and https://github.com/yarax/swagger-to-graphql/issues/51

The issue wasnt the loading, it was when you try and convert object definitions, you change the name and add a prefix, so it appears like a new object. Furthermore, you dont track the objects you've added already. So, even though loading the structure worked, the conversion had an infinite loop. I've updated the test framework because the test currently only checked that there wasnt an error, it didnt check for correctness. So, I've updated it to check that the output is correct and I've added a test for a circular dependency.

Next, the ref parser removed the refs from the object structure, so none of those definitions were ever used and produced very odd results. I've changed it so that the ref parser doesnt replace the refs since we handle them manually in the code.

The above two things have caused quite a large change in the output of the code. To see the difference compare test/fixtures/petstore.graphql and test/fixtures/petstore.graphql.old (which is what the code produced before this PR).

### CODE REVIEW

**Comment by 4F2E4A2E** [comment]
I was working in the exact same thing,
good job!

**Comment by 4F2E4A2E** [comment]
@ofersadgat you forgot to add chai as a dev depency:
```
--- package.json	(revision 9d74899e3016a62d06111f4bc25e7533549e4365)
+++ package.json	(date 1518769369456)
@@ -25,6 +25,7 @@
     "babel-plugin-transform-runtime": "^6.23.0",
     "babel-preset-es2015": "^6.24.1",
     "babel-preset-stage-0": "^6.24.1",
+    "chai": "^4.1.2",
     "eslint": "^3.19.0",
     "eslint-config-airbnb-es5": "^1.1.0",
     "eslint-plugin-react": "^6.5.0",
```

**Comment by yarax** [comment]
Hi @ofersadgat 
Thanks for PR!
Sounds reasonable, I'll have a look in the weekend 
@4F2E4A2E also thanks for help

**Comment by 4F2E4A2E** [comment]
@ofersadgat there is maybe an issue you wanna fix for PATCH | POST | PUT  requests which also share the same type with GET:

GET | findPetsByStatus has a response of Pet ("$ref": "#/definitions/Pet")
```graphql
findPetsByStatus(status: [String]): [Pet]
```

but only a input type of Pet were generated: 
```graphql
input Pet {
  id: String
  category: Category
  name: String
  photoUrls: [String]
  tags: [Tag]

  """pet status in the store"""
  status: String
}
```

**Comment by 4F2E4A2E** [comment]
This could be added to the test at the end:
```patch
===================================================================
--- test/index.js	(date 1518769433000)
+++ test/index.js	(date 1518784682212)
@@ -12,9 +12,11 @@
           .then((schema) => {
             const graphqlfile = directory + (file.replace('.json', '.graphql'));
             const graphschema = graphql.printSchema(schema);
-            const expected = fs.readFileSync(graphqlfile, "utf8");
+            const expected = fs.readFileSync(graphqlfile, 'utf8');
 
             expect(graphschema).to.equal(expected);
+            graphql.graphql(schema, '{ findPetsByStatus(status: "3") } ')
+                  .then(f => console.log(JSON.stringify(f)));
           });
       });
     }
```

The query may vary of course.

**Comment by 4F2E4A2E** [comment]
Aaand this is how the circular.json could look like:
```patch
===================================================================
--- test/fixtures/circular.json	(date 1518769433000)
+++ test/fixtures/circular.json	(date 1518785428828)
@@ -34,6 +34,35 @@
                     }
                 }
             }
+        },
+        "/swagger-graphql/patch/circular": {
+            "patch": {
+                "description": "A retrieves a circular structure",
+                "parameters": [
+                    {
+                        "in": "body",
+                        "name": "body",
+                        "required": false,
+                        "schema": {
+                            "$ref": "#/definitions/Circular"
+                        }
+                    }
+                ],
+                "produces": [
+                    "application/json"
+                ],
+                "responses": {
+                    "200": {
+                        "description": null,
+                        "schema": {
+                            "type": "array",
+                            "items": {
+                                "$ref": "#/definitions/Circular"
+                            }
+                        }
+                    }
+                }
+            }
         }
     },
     "definitions": {
```

This process could be done [easier](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) :)

**Comment by ofersadgat** [comment]
@4F2E4A2E I've fixed the chai inclusion. I didnt realize that you couldnt reuse the types so I've changed it to duplicate the definition one being an input (and ending with the name 'Input') and the other being normal. If you have another idea for the naming (or how to improve that) im all ears.

I also thing you're confused about how the test framework works. The test framework takes a pair of files: circular.json and circular.graphql and basically makes sure that given the swagger definition in circular.json we get the expected graphql output in circular.graphql. So, if you want to update what the result of the test should be you go to circular.graphql and change it there.

**Comment by 4F2E4A2E** [comment]
>  I didnt realize that you couldnt reuse the types so I've changed it to duplicate the definition one being an input (and ending with the name 'Input') and the other being normal. If you have another idea for the naming (or how to improve that) im all ears.

I recommend not to modify the object names and rather resolve it without the input string appendix, as far as i know this is totally fine by graphql-schema, **since it's being unique by the type itself**:  `type Circular` and `input Circular`.

> I also think you're confused about how the test framework works. The test framework takes a pair of files: circular.json and circular.graphql and basically makes sure that given the swagger definition in circular.json we get the expected graphql output in circular.graphql.

No i am not confused, just made a propose which is not in your intent for this test. My intention was to qualify and improve the meaning of the test by testing those definitions if they really do work with a graphql instance. We can do that in another test no problem at all.

And since we are at it, i think the code might still have some bug, i discovered that with my confused test 🗡 :)

```graphql
findPetsByStatus(status: [String]): [PetInput]
```
`
{"errors":[{"message":"The type of viewer.findPetsByStatus must be Output Type but got: [PetInput]."},{"message":"The type of viewer.findPetsByTags must be Output Type but got: [PetInput]."},{"message":"The type of viewer.getPetById must be Output Type but got: PetInput."},{"message":"The type of viewer.getUserByName must be Output Type but got: UserInput."}]}`

Anyhow, you are welcome 👍

**Comment by ofersadgat** [comment]
@4F2E4A2E Thanks for the catch! The test has been corrected to include the correct result.

Yeah, if you'd like you can create a separate test to test that the queries work. As for the naming, I dont think thats legal. Multiple threads seem to support that statement. For example: https://github.com/apollographql/graphql-tools/issues/179

**Comment by ofersadgat** [comment]
P.S. I've also added compatibility for the server field. This makes passing swagger entirely self contained in specifying how to request the resources.

**Comment by 4F2E4A2E** [comment]
Great work @ofersadgat, first tests are looking good. Starting further tests now...

**Comment by gustaflindqvist** [comment]
Great work both @ofersadgat and @4F2E4A2E! Good discussion and solving the problem. 👍🏻👏🏻

**Comment by 4F2E4A2E** [comment]
@Naming: i like the explicit side of it, though afaik , this is a valid graphql schema:
```
type Circular {
  name: String
  reference: Circular
}

input Circular {
  name: String
  reference: Circular
}
```

All operations on a complex schema are running just fine. @yarax from my end it's a go 👍

**Comment by ofersadgat** [comment]
@4F2E4A2E I tried inputting the schema as you defined it to graphql and I get an exception:

Error: Schema must contain unique named types but contains multiple types named "Pet".
      at invariant (node_modules\graphql\jsutils\invariant.js:19:11)
      at typeMapReducer (node_modules\graphql\type\schema.js:197:58)
      at Array.reduce (native)
      at node_modules\graphql\type\schema.js:221:36
      at Array.forEach (native)
      at typeMapReducer (node_modules\graphql\type\schema.js:214:27)
      at Array.reduce (native)
      at new GraphQLSchema (node_modules\graphql\type\schema.js:111:34)
      at schemaFromEndpoints (lib\index.js:75:10)
      at _callee2$ (lib\index.js:145:22)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:296:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:114:21)
      at step (node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
      at node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13

So, I dont think that is allowed.

**Comment by 4F2E4A2E** [comment]
@ofersadgat you're right, it is not possible.

**Comment by yarax** [comment]
Thanks guys, I looked through the code, looks fine. I'll merge it soon and publish as a new version

**Comment by yarax** [comment]
Available in v.1.2.4

**Pull request merged**
