### PR TITLE
Feature/es7

### PR DESCRIPTION
**Pull request by sibelius**
I have this issue https://github.com/yarax/swagger-to-graphql/issues/12

after the refactor

### CODE REVIEW

**Comment by yarax** [comment]
Hey!
Thank you very much for a great job! Sorry for response delay
After building the fork I got the error:

```
/home/roman/sandbox/swagger-to-graphql/lib/index.js:111
  var _ref2 = _asyncToGenerator(regeneratorRuntime.mark(function _callee2(swaggerPath) {
                                ^

ReferenceError: regeneratorRuntime is not defined
    at /home/roman/sandbox/swagger-to-graphql/lib/index.js:111:33
```

**Comment by sibelius** [comment]
we need to use babel-polyfill to make async await works

`import 'babel-polyfill';`

**Comment by yarax** [comment]
Also sadly that backward compatibility for src/index is broken now (it exported default object) but seems like it must to be done

**Comment by sibelius** [comment]
feel free to improve this branch in another branch or in this one as well

**Comment by yarax** [comment]
Created https://github.com/yarax/swagger-to-graphql/tree/release-1.1 branch based on your fork which will also require last issues

**Pull request merged**
