### PR TITLE
Handle paths without success responses (again)

### LINKED ISSUE #15: path item parameters not supported by the swagger parser
I'm seeing this error when using [Path Item Object parameters](http://swagger.io/specification/#path-item-object-32) in a swagger schema (attached below). It seems the [parser code](https://github.com/yarax/swagger-to-graphql/blob/master/lib/swagger.js#L47) assumes there cannot be any parameters under a path, but only methods (http verbs). The swagger spec allows `parameters` as fixed fields under `Path Item`:

> A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there.

Is this a built-in assumption meant to simplify the parser ?

```
  1) api schema converting:
     TypeError: Cannot convert undefined or null to object
      at getSuccessResponse (lib/swagger.js:21:10)
      at Object.keys.forEach.method (lib/swagger.js:58:19)
      at Array.forEach (native)
      at Object.keys.forEach.path (lib/swagger.js:47:24)
      at Array.forEach (native)
      at getAllEndPoints (lib/swagger.js:45:29)
      at loadSchema.then.swaggerSchema (lib/index.js:9:23)
```
[api-spec.json](https://github.com/yarax/swagger-to-graphql/files/965087/api.json.txt)

### LINKED ISSUE #20: Cannot convert undefined or null to object in getSuccessResponse
```
Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getSuccessResponse (/xxx/node_modules/swagger-to-graphql/lib/swagger.js:21:10)
```

Swagger-to-graphql version is 1.0.5.

The schema that I have used: https://raw.githubusercontent.com/tylerlong/rc-codegen/master/common/swagger.json

The schema has been validated with https://github.com/Yelp/swagger_spec_validator.

### PR DESCRIPTION
**Pull request by steverice**
This check was added in 601ac79680d293052a999ecee92de058d78441e0 to fix #20 and fix #15, but was removed in 21a37357b7dd6c1f4dd575c24aaa8ce95e433b02.

### CODE REVIEW

**Comment by yarax** [comment]
Hi @0xR, was the deletion done on purpose?
@steverice Can you please check the failed linting

**Comment by steverice** [comment]
@yarax sorry about that, should be fixed now.

**Comment by 0xR** [comment]
Yes, responses is required in the operation object: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object

I don't think we should try to support invalid openapi schemas.

**Comment by 0xR** [comment]
Note the code currently does accept an empty responses object. While the spec is clear:

> The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call.

**Pull request closed without merging**
